import { describe, it, expect, afterEach } from 'vitest'
import fs from 'fs'
import path from 'path'
import os from 'os'
import type { ResolvedConfig } from '../../../config/types.js'
import { generateAppleTokens } from '../../../schema/generators/apple/tokens.js'

function makeTempConfig(tokens: object): { config: ResolvedConfig; dir: string } {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sentinel-test-'))
  const schemasDir = path.join(dir, 'schemas')
  const designDir = path.join(schemasDir, 'design')
  fs.mkdirSync(designDir, { recursive: true })

  fs.writeFileSync(path.join(designDir, 'tokens.json'), JSON.stringify(tokens))

  const outputPath = path.join(dir, 'output', 'Tokens.swift')

  const config: ResolvedConfig = {
    sentinel: '1.0',
    project: 'testapp',
    version: '1.0.0',
    projectRoot: dir,
    sentinelDir: dir,
    schemasDir,
    featuresDir: path.join(schemasDir, 'features'),
    designDir,
    platformDir: path.join(schemasDir, 'platform'),
    modelsDir: path.join(schemasDir, 'models'),
    platforms: {
      apple: {
        path: './apple',
        language: 'swift',
        output: {
          tokens: outputPath,
          strings: path.join(dir, 'output', 'Strings.swift'),
          flags: path.join(dir, 'output', 'FeatureFlags.swift'),
        },
      },
    },
  }

  return { config, dir }
}

describe('generateAppleTokens', () => {
  let dir: string

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true })
  })

  it('generates Swift enum with header, hash, and token sections', () => {
    const { config, dir: d } = makeTempConfig({
      $sentinel: '1.0',
      type: 'tokens',
      version: '1.0.0',
      colors: {
        brand: {
          primary: { value: '#FF5733' },
        },
      },
      typography: {
        fontSizes: {
          base: { value: '16px' },
          '2xl': { value: '24px' },
        },
        lineHeights: {
          normal: { value: '1.5' },
          '2xl': { value: '1.75' },
        },
      },
      spacing: {
        4: { value: '16px' },
      },
    })
    dir = d

    generateAppleTokens(config)
    const output = fs.readFileSync(config.platforms.apple!.output.tokens!, 'utf-8')

    expect(output).toContain('GENERATED BY SENTINEL')
    expect(output).toContain('// Hash:')
    // Class name is derived from the output filename (Tokens.swift → Tokens)
    expect(output).toContain('public enum Tokens')
    expect(output).toContain('import SwiftUI')

    // Colors use `Color(hex: ...)` format
    expect(output).toContain('Color(hex: "#FF5733")')

    // Typography uses `public static let base: CGFloat = 16`
    expect(output).toContain('public static let base: CGFloat = 16')
    expect(output).toContain('public static let s2xl: CGFloat = 24')

    // LineHeight
    expect(output).toContain('public static let normal: CGFloat = 1.5')
    expect(output).toContain('public static let s2xl: CGFloat = 1.75')

    // Spacing: numeric key gets 's' prefix
    expect(output).toContain('public static let s4: CGFloat = 16')
    expect(output).toContain('public enum AppTokensColorBrand')
    expect(output).toContain('public enum AppTokensSpacing')
    expect(output).toContain('public static let smd = Tokens.Spacing.md')
  })

  it('handles nested color enum structure', () => {
    const { config, dir: d } = makeTempConfig({
      $sentinel: '1.0',
      type: 'tokens',
      version: '1.0.0',
      colors: {
        semantic: {
          background: {
            primary: { value: '#FFFFFF' },
            secondary: { value: '#F5F5F5' },
          },
        },
      },
      typography: {},
      spacing: {},
    })
    dir = d

    generateAppleTokens(config)
    const output = fs.readFileSync(config.platforms.apple!.output.tokens!, 'utf-8')

    expect(output).toContain('public enum Semantic')
    expect(output).toContain('public enum Background')
    expect(output).toContain('Color(hex: "#FFFFFF")')
    expect(output).toContain('Color(hex: "#F5F5F5")')
  })

  it('generates borderRadius and animation sections when present', () => {
    const { config, dir: d } = makeTempConfig({
      $sentinel: '1.0',
      type: 'tokens',
      version: '1.0.0',
      colors: {},
      typography: {},
      spacing: {},
      borderRadius: {
        md: { value: '8px' },
        full: { value: '9999px' },
      },
      animation: {
        duration: {
          fast: { value: '150ms' },
        },
      },
    })
    dir = d

    generateAppleTokens(config)
    const output = fs.readFileSync(config.platforms.apple!.output.tokens!, 'utf-8')

    expect(output).toContain('public enum CornerRadius')
    expect(output).toContain('public static let md: CGFloat = 8')
    expect(output).toContain('public static let full: CGFloat = 9999')

    expect(output).toContain('public enum Animation')
    // Animation duration is stored in seconds (150ms = 0.15)
    expect(output).toContain('public static let fast: Double = 0.15')
  })

  it('embeds schema hash that can be used for staleness detection', () => {
    const { config, dir: d } = makeTempConfig({
      $sentinel: '1.0', type: 'tokens', version: '1.0.0',
      colors: {}, typography: {}, spacing: {},
    })
    dir = d

    generateAppleTokens(config)
    const output = fs.readFileSync(config.platforms.apple!.output.tokens!, 'utf-8')

    // Hash line must be present and be 16 hex chars
    const match = output.match(/\/\/ Hash:\s+([a-f0-9]+)/)
    expect(match).toBeTruthy()
    expect(match![1]).toHaveLength(16)
  })
})
