import { describe, it, expect, afterEach } from 'vitest'
import fs from 'fs'
import path from 'path'
import os from 'os'
import type { ResolvedConfig } from '../../../config/types.js'
import { generateGoogleTokens } from '../../../schema/generators/google/tokens.js'

function makeTempConfig(tokens: object): { config: ResolvedConfig; dir: string } {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sentinel-test-'))
  const schemasDir = path.join(dir, 'schemas')
  const designDir = path.join(schemasDir, 'design')
  fs.mkdirSync(designDir, { recursive: true })
  fs.writeFileSync(path.join(designDir, 'tokens.json'), JSON.stringify(tokens))

  const outputPath = path.join(dir, 'output', 'kotlin', 'com', 'testapp', 'design', 'TestappTokens.kt')

  const config: ResolvedConfig = {
    sentinel: '1.0',
    project: 'testapp',
    version: '1.0.0',
    projectRoot: dir,
    sentinelDir: dir,
    schemasDir,
    featuresDir: path.join(schemasDir, 'features'),
    designDir,
    platformDir: path.join(schemasDir, 'platform'),
    modelsDir: path.join(schemasDir, 'models'),
    platforms: {
      google: {
        path: './google',
        language: 'kotlin',
        output: {
          tokens: outputPath,
          strings: path.join(dir, 'output', 'strings.xml'),
          flags: path.join(dir, 'output', 'kotlin', 'com', 'testapp', 'core', 'FeatureFlags.kt'),
        },
      },
    },
  }

  return { config, dir }
}

describe('generateGoogleTokens', () => {
  let dir: string

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true })
  })

  it('generates correct Kotlin Color values (no double FF prefix)', () => {
    const { config, dir: d } = makeTempConfig({
      $sentinel: '1.0',
      type: 'tokens',
      version: '1.0.0',
      colors: {
        brand: {
          primary: { value: '#FF5733' },
        },
      },
      typography: {
        fontSizes: { base: { value: '16px' } },
        lineHeights: { normal: { value: '1.5' } },
      },
      spacing: { 4: { value: '16px' } },
    })
    dir = d

    generateGoogleTokens(config)
    const output = fs.readFileSync(config.platforms.google!.output.tokens!, 'utf-8')

    // Critical regression test: must be 0xFF + 6 hex chars = 8 chars total, not 10
    expect(output).toContain('Color(0xFFFF5733)')
    expect(output).not.toContain('Color(0xFFFFFF5733)')  // the old bug
    expect(output).toContain('GENERATED BY SENTINEL')
    expect(output).toContain('// Hash:')
    expect(output).toContain('object TestappTokens')
    expect(output).toContain('val base = 16.sp')
    expect(output).toContain('val s4 = 16.dp')
  })

  it('handles full (pill) border radius as 999.dp', () => {
    const { config, dir: d } = makeTempConfig({
      $sentinel: '1.0',
      type: 'tokens',
      version: '1.0.0',
      colors: {},
      typography: {},
      spacing: {},
      borderRadius: {
        full: { value: '9999px' },
        sm: { value: '4px' },
      },
    })
    dir = d

    generateGoogleTokens(config)
    const output = fs.readFileSync(config.platforms.google!.output.tokens!, 'utf-8')

    expect(output).toContain('val full = 9999.dp')
    expect(output).toContain('val sm = 4.dp')
  })

  it('derives package from output path', () => {
    const { config, dir: d } = makeTempConfig({
      $sentinel: '1.0',
      type: 'tokens',
      version: '1.0.0',
      colors: {},
      typography: {},
      spacing: {},
    })
    dir = d

    generateGoogleTokens(config)
    const output = fs.readFileSync(config.platforms.google!.output.tokens!, 'utf-8')
    expect(output).toContain('package com.testapp.design')
  })
})
