import { describe, it, expect, afterEach } from 'vitest'
import fs from 'fs'
import path from 'path'
import os from 'os'
import type { ResolvedConfig, ModelSchema } from '../../../config/types.js'
import { generateAppleModels } from '../../../schema/generators/apple/models.js'
import { generateGoogleModels } from '../../../schema/generators/google/models.js'

function makeTempConfig(models: ModelSchema[]): { config: ResolvedConfig; dir: string } {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sentinel-test-'))
  const schemasDir = path.join(dir, 'schemas')
  const modelsDir = path.join(schemasDir, 'models')
  fs.mkdirSync(modelsDir, { recursive: true })

  for (const model of models) {
    fs.writeFileSync(path.join(modelsDir, `${model.id}.json`), JSON.stringify(model))
  }

  const appleModelsOutput = path.join(dir, 'output', 'Models.swift')
  const kotlinModelsOutput = path.join(dir, 'output', 'kotlin', 'com', 'testapp', 'models', 'Models.kt')

  const config: ResolvedConfig = {
    sentinel: '1.0',
    project: 'testapp',
    version: '1.0.0',
    projectRoot: dir,
    sentinelDir: dir,
    schemasDir,
    featuresDir: path.join(schemasDir, 'features'),
    designDir: path.join(schemasDir, 'design'),
    platformDir: path.join(schemasDir, 'platform'),
    modelsDir,
    platforms: {
      apple: {
        path: './apple',
        language: 'swift',
        output: {
          tokens: path.join(dir, 'Tokens.swift'),
          strings: path.join(dir, 'Strings.swift'),
          flags: path.join(dir, 'Flags.swift'),
          models: appleModelsOutput,
        },
      },
      google: {
        path: './google',
        language: 'kotlin',
        output: {
          tokens: path.join(dir, 'Tokens.kt'),
          strings: path.join(dir, 'strings.xml'),
          flags: path.join(dir, 'Flags.kt'),
          models: kotlinModelsOutput,
        },
      },
    },
  }

  return { config, dir }
}

describe('generateAppleModels', () => {
  let dir: string

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true })
  })

  it('generates Swift enum from enum model schema', () => {
    const { config, dir: d } = makeTempConfig([{
      $sentinel: '1.0',
      type: 'model',
      id: 'workout-status',
      name: 'WorkoutStatus',
      isEnum: true,
      platforms: ['apple', 'google'],
      enumValues: [
        { name: 'active', rawValue: 'active' },
        { name: 'completed', rawValue: 'completed' },
        { name: 'abandoned', rawValue: 'abandoned' },
      ],
    }])
    dir = d

    generateAppleModels(config)
    const output = fs.readFileSync(config.platforms.apple!.output.models!, 'utf-8')

    expect(output).toContain('GENERATED BY SENTINEL')
    expect(output).toContain('public enum WorkoutStatus: String, Codable, CaseIterable')
    expect(output).toContain('case active')
    expect(output).toContain('case completed')
    expect(output).toContain('case abandoned')
  })

  it('generates Swift struct from regular model schema', () => {
    const { config, dir: d } = makeTempConfig([{
      $sentinel: '1.0',
      type: 'model',
      id: 'workout-log',
      name: 'WorkoutLog',
      description: 'A completed workout',
      platforms: ['apple', 'google'],
      fields: [
        { name: 'id', type: 'String', optional: false },
        { name: 'durationSeconds', type: 'Int', optional: true },
        { name: 'notes', type: 'String', optional: true },
      ],
    }])
    dir = d

    generateAppleModels(config)
    const output = fs.readFileSync(config.platforms.apple!.output.models!, 'utf-8')

    expect(output).toContain('/// A completed workout')
    expect(output).toContain('public struct WorkoutLog: Codable, Identifiable')
    expect(output).toContain('public var id: String')
    expect(output).toContain('public var durationSeconds: Int?')
  })

  it('generates array types correctly', () => {
    const { config, dir: d } = makeTempConfig([{
      $sentinel: '1.0',
      type: 'model',
      id: 'workout',
      name: 'Workout',
      platforms: ['apple'],
      fields: [
        { name: 'exerciseLogs', type: 'ExerciseLog', optional: false, isArray: true },
        { name: 'tags', type: 'String', optional: true, isArray: true },
      ],
    }])
    dir = d

    generateAppleModels(config)
    const output = fs.readFileSync(config.platforms.apple!.output.models!, 'utf-8')

    expect(output).toContain('public var exerciseLogs: [ExerciseLog]')
    expect(output).toContain('public var tags: [String]?')
  })
})

describe('generateGoogleModels', () => {
  let dir: string

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true })
  })

  it('generates Kotlin enum from enum model schema', () => {
    const { config, dir: d } = makeTempConfig([{
      $sentinel: '1.0',
      type: 'model',
      id: 'workout-status',
      name: 'WorkoutStatus',
      isEnum: true,
      platforms: ['apple', 'google'],
      enumValues: [
        { name: 'active', rawValue: 'active' },
        { name: 'completed', rawValue: 'completed' },
      ],
    }])
    dir = d

    generateGoogleModels(config)
    const output = fs.readFileSync(config.platforms.google!.output.models!, 'utf-8')

    expect(output).toContain('GENERATED BY SENTINEL')
    expect(output).toContain('@Serializable')
    expect(output).toContain('enum class WorkoutStatus')
    expect(output).toContain('ACTIVE("active")')
    expect(output).toContain('COMPLETED("completed")')
  })

  it('generates Kotlin data class', () => {
    const { config, dir: d } = makeTempConfig([{
      $sentinel: '1.0',
      type: 'model',
      id: 'workout-log',
      name: 'WorkoutLog',
      platforms: ['google'],
      fields: [
        { name: 'id', type: 'String', optional: false },
        { name: 'durationSeconds', type: 'Int', optional: true },
        { name: 'boolField', type: 'Bool', optional: false },
      ],
    }])
    dir = d

    generateGoogleModels(config)
    const output = fs.readFileSync(config.platforms.google!.output.models!, 'utf-8')

    expect(output).toContain('data class WorkoutLog(')
    expect(output).toContain('val id: String')
    expect(output).toContain('val durationSeconds: Int? = null')
    expect(output).toContain('val boolField: Boolean')
  })
})
