import { describe, it, expect, afterEach } from 'vitest'
import fs from 'fs'
import path from 'path'
import os from 'os'
import type { ResolvedConfig } from '../../../config/types.js'
import { generateAppleStrings } from '../../../schema/generators/apple/strings.js'
import { generateAppleFlags } from '../../../schema/generators/apple/flags.js'
import { generateGoogleStrings } from '../../../schema/generators/google/strings.js'
import { generateGoogleFlags } from '../../../schema/generators/google/flags.js'
import { generateWebTokens } from '../../../schema/generators/web/tokens.js'
import { generateWebStrings } from '../../../schema/generators/web/strings.js'
import { generateWebFlags } from '../../../schema/generators/web/flags.js'

function makeConfig(design: object, platform: object): { config: ResolvedConfig; dir: string } {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sentinel-test-'))
  const schemasDir = path.join(dir, 'schemas')
  fs.mkdirSync(path.join(schemasDir, 'design'), { recursive: true })
  fs.mkdirSync(path.join(schemasDir, 'platform'), { recursive: true })
  fs.writeFileSync(path.join(schemasDir, 'design', 'strings.json'), JSON.stringify(design))
  fs.writeFileSync(path.join(schemasDir, 'design', 'tokens.json'), JSON.stringify({
    $sentinel: '1.0', type: 'tokens', version: '1.0.0',
    colors: { brand: { primary: { value: '#000' } } },
    typography: { fontSizes: { base: { value: '16px' } } },
    spacing: { 4: { value: '16px' } },
  }))
  fs.writeFileSync(path.join(schemasDir, 'platform', 'feature-flags.json'), JSON.stringify(platform))

  const config: ResolvedConfig = {
    sentinel: '1.0', project: 'testapp', version: '1.0.0',
    projectRoot: dir, sentinelDir: dir, schemasDir,
    featuresDir: path.join(schemasDir, 'features'),
    designDir: path.join(schemasDir, 'design'),
    platformDir: path.join(schemasDir, 'platform'),
    modelsDir: path.join(schemasDir, 'models'),
    platforms: {
      apple: {
        path: './apple', language: 'swift',
        output: {
          tokens: path.join(dir, 'Tokens.swift'),
          strings: path.join(dir, 'Strings.swift'),
          flags: path.join(dir, 'FeatureFlags.swift'),
        },
      },
      google: {
        path: './google', language: 'kotlin',
        output: {
          tokens: path.join(dir, 'Tokens.kt'),
          strings: path.join(dir, 'strings.xml'),
          flags: path.join(dir, 'kotlin', 'com', 'testapp', 'core', 'FeatureFlags.kt'),
        },
      },
      web: {
        path: './web', language: 'typescript',
        output: {
          tokens: path.join(dir, 'tokens.css'),
          strings: path.join(dir, 'strings.ts'),
          flags: path.join(dir, 'flags.ts'),
        },
      },
    },
  }
  return { config, dir }
}

const EXAMPLE_STRINGS = {
  $sentinel: '1.0', type: 'strings', version: '1.0.0',
  locales: ['en'],
  strings: {
    'common.ok': 'OK',
    'common.cancel': 'Cancel',
    'workout.start_button': 'Start Workout',
    'common.error.generic': 'Something went wrong',
  },
}

const EXAMPLE_FLAGS = {
  $sentinel: '1.0', type: 'feature-flags', version: '1.0.0',
  flags: [
    { key: 'NEW_WORKOUT_FLOW', description: 'New flow', defaultEnabled: false, platforms: ['apple', 'google', 'web'], milestone: 1 },
    { key: 'PRO_ANALYTICS', description: 'Pro analytics', defaultEnabled: true, platforms: ['web'], milestone: 2 },
  ],
}

// ─── Apple strings ────────────────────────────────────────────────────────────

describe('generateAppleStrings', () => {
  let dir: string
  afterEach(() => fs.rmSync(dir, { recursive: true, force: true }))

  it('generates namespaced Swift string constants', () => {
    const { config, dir: d } = makeConfig(EXAMPLE_STRINGS, EXAMPLE_FLAGS)
    dir = d
    generateAppleStrings(config)
    const output = fs.readFileSync(config.platforms.apple!.output.strings!, 'utf-8')

    expect(output).toContain('GENERATED BY SENTINEL')
    expect(output).toContain('// Hash:')
    expect(output).toContain('import Foundation')
    expect(output).toContain('public enum Strings')
    expect(output).toContain('enum Common')
    expect(output).toContain('static let ok')
    expect(output).toContain('"OK"')
  })

  it('converts dot-notation to camelCase names', () => {
    const { config, dir: d } = makeConfig(EXAMPLE_STRINGS, EXAMPLE_FLAGS)
    dir = d
    generateAppleStrings(config)
    const output = fs.readFileSync(config.platforms.apple!.output.strings!, 'utf-8')
    // 'workout.start_button' → namespace Workout, key startButton
    expect(output).toContain('enum Workout')
    expect(output).toContain('startButton')
  })
})

// ─── Apple flags ──────────────────────────────────────────────────────────────

describe('generateAppleFlags', () => {
  let dir: string
  afterEach(() => fs.rmSync(dir, { recursive: true, force: true }))

  it('generates Swift FeatureFlags class with only apple-platform flags', () => {
    const { config, dir: d } = makeConfig(EXAMPLE_STRINGS, EXAMPLE_FLAGS)
    dir = d
    generateAppleFlags(config)
    const output = fs.readFileSync(config.platforms.apple!.output.flags!, 'utf-8')

    expect(output).toContain('GENERATED BY SENTINEL')
    expect(output).toContain('// Hash:')
    expect(output).toContain('public final class FeatureFlags')
    expect(output).toContain('newWorkoutFlow')        // camelCase of NEW_WORKOUT_FLOW
    expect(output).not.toContain('proAnalytics')      // web-only flag must be excluded
  })

  it('generates override mechanism', () => {
    const { config, dir: d } = makeConfig(EXAMPLE_STRINGS, EXAMPLE_FLAGS)
    dir = d
    generateAppleFlags(config)
    const output = fs.readFileSync(config.platforms.apple!.output.flags!, 'utf-8')
    expect(output).toContain('override(_')
    expect(output).toContain('overrides[key]')
  })
})

// ─── Google strings ───────────────────────────────────────────────────────────

describe('generateGoogleStrings', () => {
  let dir: string
  afterEach(() => fs.rmSync(dir, { recursive: true, force: true }))

  it('generates Android strings.xml with correct XML structure', () => {
    const { config, dir: d } = makeConfig(EXAMPLE_STRINGS, EXAMPLE_FLAGS)
    dir = d
    generateGoogleStrings(config)
    const output = fs.readFileSync(config.platforms.google!.output.strings!, 'utf-8')

    expect(output).toContain('<?xml version="1.0"')
    expect(output).toContain('GENERATED BY SENTINEL')
    expect(output).toContain('<resources>')
    expect(output).toContain('</resources>')
    expect(output).toContain('<string name="common_ok">OK</string>')
    expect(output).toContain('<string name="common_cancel">Cancel</string>')
  })

  it('converts dot.notation keys to android_underscore format', () => {
    const { config, dir: d } = makeConfig(EXAMPLE_STRINGS, EXAMPLE_FLAGS)
    dir = d
    generateGoogleStrings(config)
    const output = fs.readFileSync(config.platforms.google!.output.strings!, 'utf-8')
    expect(output).toContain('name="workout_start_button"')
  })
})

// ─── Google flags ─────────────────────────────────────────────────────────────

describe('generateGoogleFlags', () => {
  let dir: string
  afterEach(() => fs.rmSync(dir, { recursive: true, force: true }))

  it('generates Kotlin FeatureFlags object with only google-platform flags', () => {
    const { config, dir: d } = makeConfig(EXAMPLE_STRINGS, EXAMPLE_FLAGS)
    dir = d
    generateGoogleFlags(config)
    const output = fs.readFileSync(config.platforms.google!.output.flags!, 'utf-8')

    expect(output).toContain('GENERATED BY SENTINEL')
    expect(output).toContain('// Hash:')
    expect(output).toContain('object FeatureFlags')
    expect(output).toContain('newWorkoutFlow')
    expect(output).not.toContain('proAnalytics')
  })
})

// ─── Web generators ───────────────────────────────────────────────────────────

describe('generateWebTokens', () => {
  let dir: string
  afterEach(() => fs.rmSync(dir, { recursive: true, force: true }))

  it('generates CSS :root variables for .css output path', () => {
    const { config, dir: d } = makeConfig(EXAMPLE_STRINGS, EXAMPLE_FLAGS)
    dir = d
    generateWebTokens(config)
    // The test config uses tokens.css — should produce CSS custom properties only
    const output = fs.readFileSync(config.platforms.web!.output.tokens!, 'utf-8')

    expect(output).toContain('GENERATED BY SENTINEL')
    expect(output).toContain(':root {')
    expect(output).toContain('--color-')
    expect(output).not.toContain('export const tokens')
  })

  it('generates TypeScript exports for .ts output path', () => {
    const { config, dir: d } = makeConfig(EXAMPLE_STRINGS, EXAMPLE_FLAGS)
    dir = d
    // Override to use .ts extension
    const tsPath = config.platforms.web!.output.tokens!.replace('.css', '.ts')
    config.platforms.web!.output.tokens = tsPath
    generateWebTokens(config)
    const output = fs.readFileSync(tsPath, 'utf-8')

    expect(output).toContain('GENERATED BY SENTINEL')
    expect(output).toContain('export const tokens')
    expect(output).not.toContain(':root {')
  })
})

describe('generateWebStrings', () => {
  let dir: string
  afterEach(() => fs.rmSync(dir, { recursive: true, force: true }))

  it('generates nested TypeScript strings object', () => {
    const { config, dir: d } = makeConfig(EXAMPLE_STRINGS, EXAMPLE_FLAGS)
    dir = d
    generateWebStrings(config)
    const output = fs.readFileSync(config.platforms.web!.output.strings!, 'utf-8')

    expect(output).toContain('GENERATED BY SENTINEL')
    expect(output).toContain('export const strings')
    expect(output).toContain('"OK"')
  })
})

describe('generateWebFlags', () => {
  let dir: string
  afterEach(() => fs.rmSync(dir, { recursive: true, force: true }))

  it('generates TypeScript feature flags with getters', () => {
    const { config, dir: d } = makeConfig(EXAMPLE_STRINGS, EXAMPLE_FLAGS)
    dir = d
    generateWebFlags(config)
    const output = fs.readFileSync(config.platforms.web!.output.flags!, 'utf-8')

    expect(output).toContain('GENERATED BY SENTINEL')
    expect(output).toContain('newWorkoutFlow')
    expect(output).toContain('proAnalytics')    // both flags are web-platform
  })
})
