/**
 * Report Builder
 * Generates Markdown and HTML reports from Sentinel results.
 * Writes to GITHUB_STEP_SUMMARY when available (GitHub Actions native summary).
 */
import fs from 'fs'
import path from 'path'
import type { SentinelReport } from '../config/types.js'

const STATUS_EMOJI = {
  pass: '✅',
  fail: '❌',
  warn: '⚠️',
  info: 'ℹ️',
}

export function buildMarkdownReport(report: SentinelReport, analysis?: { summary: string; prioritisedActions: Array<{ action: string; priority: string; layer: string }> } | null): string {
  const overall = report.passed ? STATUS_EMOJI.pass : STATUS_EMOJI.fail
  const lines: string[] = [
    `# ${overall} Sentinel Report — ${report.project} v${report.version}`,
    ``,
    `**Time:** ${report.timestamp}  `,
    `**Result:** ${report.passed ? 'PASSED' : 'FAILED'}  `,
    `**Errors:** ${report.summary.errors}  **Warnings:** ${report.summary.warnings}`,
    ``,
    `## Results by Layer`,
    ``,
    `| Layer | Status | Checks | Errors | Duration |`,
    `|-------|--------|--------|--------|----------|`,
  ]

  for (const result of report.results) {
    const badge = result.passed ? STATUS_EMOJI.pass : STATUS_EMOJI.fail
    const errors = result.issues.filter(i => i.severity === 'error').length
    lines.push(
      `| ${result.layer} | ${badge} | ${result.checkedCount} | ${errors} | ${result.durationMs}ms |`
    )
  }

  lines.push(``)

  // Issues detail
  const allErrors = report.results.flatMap(r => r.issues.filter(i => i.severity === 'error'))
  const allWarnings = report.results.flatMap(r => r.issues.filter(i => i.severity === 'warning'))

  if (allErrors.length > 0) {
    lines.push(`## ${STATUS_EMOJI.fail} Errors (${allErrors.length})`, ``)
    for (const issue of allErrors) {
      lines.push(`### \`[${issue.layer}/${issue.rule}]\``)
      lines.push(`> ${issue.message}`)
      if (issue.file) lines.push(`**File:** \`${issue.file}\`  `)
      if (issue.fix) lines.push(`**Fix:** ${issue.fix}`)
      lines.push(``)
    }
  }

  if (allWarnings.length > 0) {
    lines.push(`## ${STATUS_EMOJI.warn} Warnings (${allWarnings.length})`, ``)
    lines.push(`<details><summary>Show warnings</summary>`, ``)
    for (const issue of allWarnings) {
      lines.push(`- **[${issue.layer}/${issue.rule}]** ${issue.message}`)
    }
    lines.push(``, `</details>`, ``)
  }

  // AI analysis
  if (analysis) {
    lines.push(`## 🧠 Brain Analysis`, ``)
    lines.push(`> ${analysis.summary}`, ``)
    if (analysis.prioritisedActions.length > 0) {
      lines.push(`### Prioritised Actions`, ``)
      for (const action of analysis.prioritisedActions) {
        const badge = action.priority === 'critical' ? '🔴' :
                      action.priority === 'high' ? '🟠' :
                      action.priority === 'medium' ? '🟡' : '🟢'
        lines.push(`- ${badge} **[${action.layer}]** ${action.action}`)
      }
      lines.push(``)
    }
  }

  lines.push(`---`)
  lines.push(`*Generated by [Sentinel](https://github.com/czaku/sentinel) at ${report.timestamp}*`)

  return lines.join('\n')
}

export function buildHtmlReport(report: SentinelReport): string {
  const md = buildMarkdownReport(report)
  // Basic HTML wrapper — projects can replace with their own template
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sentinel Report — ${report.project}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; }
    h1 { border-bottom: 2px solid #e5e7eb; padding-bottom: 12px; }
    table { border-collapse: collapse; width: 100%; }
    th, td { border: 1px solid #e5e7eb; padding: 8px 12px; text-align: left; }
    th { background: #f9fafb; }
    code { background: #f3f4f6; padding: 2px 6px; border-radius: 4px; font-size: 0.875em; }
    blockquote { border-left: 4px solid #e5e7eb; margin: 0; padding-left: 16px; color: #6b7280; }
    details summary { cursor: pointer; color: #6b7280; }
  </style>
</head>
<body>
  <pre>${escapeHtml(md)}</pre>
</body>
</html>`
}

/** Write report to GITHUB_STEP_SUMMARY if running in GitHub Actions */
export function writeToGitHubSummary(report: SentinelReport, analysis?: Parameters<typeof buildMarkdownReport>[1]): void {
  const summaryPath = process.env.GITHUB_STEP_SUMMARY
  if (!summaryPath) return

  const markdown = buildMarkdownReport(report, analysis)
  fs.appendFileSync(summaryPath, markdown + '\n')
}

/** Write report to a file */
export function writeReportFile(outputPath: string, report: SentinelReport, format: 'md' | 'html' = 'md'): void {
  const content = format === 'html' ? buildHtmlReport(report) : buildMarkdownReport(report)
  fs.mkdirSync(path.dirname(outputPath), { recursive: true })
  fs.writeFileSync(outputPath, content, 'utf-8')
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}
