import { describe, it, expect, afterEach } from 'vitest'
import fs from 'fs'
import path from 'path'
import os from 'os'
import type { ResolvedConfig } from '../../../config/types.js'
import { checkStaleness } from '../../../schema/validators/staleness.js'
import { hashFile } from '../../../utils/file.js'

function makeConfig(): { config: ResolvedConfig; dir: string } {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sentinel-test-'))
  const schemasDir = path.join(dir, 'schemas')
  fs.mkdirSync(path.join(schemasDir, 'design'), { recursive: true })
  fs.mkdirSync(path.join(schemasDir, 'platform'), { recursive: true })

  const config: ResolvedConfig = {
    sentinel: '1.0',
    project: 'testapp',
    version: '1.0.0',
    projectRoot: dir,
    sentinelDir: dir,
    schemasDir,
    featuresDir: path.join(schemasDir, 'features'),
    designDir: path.join(schemasDir, 'design'),
    platformDir: path.join(schemasDir, 'platform'),
    modelsDir: path.join(schemasDir, 'models'),
    platforms: {
      apple: {
        path: './apple',
        language: 'swift',
        output: {
          tokens: path.join(dir, 'output', 'Tokens.swift'),
          strings: path.join(dir, 'output', 'Strings.swift'),
          flags: path.join(dir, 'output', 'FeatureFlags.swift'),
        },
      },
    },
  }

  return { config, dir }
}

describe('checkStaleness', () => {
  let dir: string

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true })
  })

  it('reports error when generated file is missing', () => {
    const { config, dir: d } = makeConfig()
    dir = d

    // Create schema but no generated output
    fs.writeFileSync(
      path.join(config.designDir, 'tokens.json'),
      JSON.stringify({ $sentinel: '1.0', type: 'tokens', version: '1.0.0', colors: {}, typography: {}, spacing: {} })
    )

    const result = checkStaleness(config)
    const errors = result.issues.filter(i => i.severity === 'error')
    expect(errors.some(e => e.message.includes('apple/tokens'))).toBe(true)
  })

  it('passes when embedded hash matches current schema', () => {
    const { config, dir: d } = makeConfig()
    dir = d

    const schemaContent = JSON.stringify({ $sentinel: '1.0', type: 'tokens', version: '1.0.0', colors: {}, typography: {}, spacing: {} })
    const schemaPath = path.join(config.designDir, 'tokens.json')
    fs.writeFileSync(schemaPath, schemaContent)

    const hash = hashFile(schemaPath)

    // Write a generated file with the correct embedded hash
    const outputPath = config.platforms.apple!.output.tokens!
    fs.mkdirSync(path.dirname(outputPath), { recursive: true })
    fs.writeFileSync(outputPath, [
      `// GENERATED BY SENTINEL — DO NOT EDIT BY HAND`,
      `// Tool:   sentinel/generators/apple/tokens`,
      `// Source: sentinel/schemas/design/tokens.json`,
      `// Hash:   ${hash}`,
      `// Run "sentinel schema:generate" to regenerate`,
      `enum TestappTokens {}`,
    ].join('\n'))

    const result = checkStaleness(config)
    const errors = result.issues.filter(i => i.severity === 'error')
    // Should have no errors for tokens (strings and flags will have missing-file errors)
    const tokenErrors = errors.filter(e => e.message.includes('apple/tokens'))
    expect(tokenErrors).toHaveLength(0)
  })

  it('reports error when embedded hash does not match current schema', () => {
    const { config, dir: d } = makeConfig()
    dir = d

    const schemaPath = path.join(config.designDir, 'tokens.json')
    fs.writeFileSync(schemaPath, JSON.stringify({ version: '1', colors: {}, typography: {}, spacing: {} }))

    // Generated file has a stale (wrong) hash
    const outputPath = config.platforms.apple!.output.tokens!
    fs.mkdirSync(path.dirname(outputPath), { recursive: true })
    fs.writeFileSync(outputPath, [
      `// GENERATED BY SENTINEL`,
      `// Hash:   000000000000dead`,  // wrong hash
      `enum TestappTokens {}`,
    ].join('\n'))

    const result = checkStaleness(config)
    const errors = result.issues.filter(i => i.severity === 'error' && i.message.includes('apple/tokens'))
    expect(errors).toHaveLength(1)
  })
})
